plugins {
    id 'com.android.library'
}

android {
    namespace 'noxmon.autoinstall'
    compileSdk = 35

    defaultConfig {
        minSdkVersion 21
    }

    buildTypes {
        debug {}
        proguard {
            initWith debug
        }
        proguardNoDebug {
            initWith proguard
            debuggable false
        }
        release {}
        gplay {
            initWith release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
