plugins {
    id 'com.android.application'
}

android {
    namespace 'com.noxmotion.real'
    compileSdk 35

    defaultConfig {
        applicationId 'com.noxmotion.real'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
